name: 'Clone issue'
description: 'Clone issue to another repository based on label'
inputs:
  token:  
    description: 'Github token with repo:all permission'
    required: true
  targetRepo:
    description: 'The repository in which to copy the issue'
    required: true
  sourceLabel:
    description: 'The source label on which to act'
    default: 'clone'
    required: false
  destinationLabel:
    description: 'The label to be used on the cloned issue'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'alert-circle'
  color: 'green'
